In [63]:
#import the NumPy Library as np variable
import numpy as np

In [64]:
#define a np variable with all ones
a = np.ones((3,3))

In [65]:
#print a 
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [66]:
b = np.zeros((3,3))

In [67]:
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [68]:
a+b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [69]:
r = np.random.randint(10,100,(4,4))

In [70]:
r

array([[20, 21, 59, 27],
       [82, 74, 44, 76],
       [95, 30, 94, 46],
       [42, 86, 54, 16]])

In [71]:
np.ones((3,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [72]:
con = np.concatenate([a,b])

In [73]:
con

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [74]:
np.concatenate([a,b],axis=1)

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

In [75]:
r

array([[20, 21, 59, 27],
       [82, 74, 44, 76],
       [95, 30, 94, 46],
       [42, 86, 54, 16]])

In [76]:
r.shape

(4, 4)

In [77]:
a.shape

(3, 3)

In [78]:
r.reshape(2,8)

array([[20, 21, 59, 27, 82, 74, 44, 76],
       [95, 30, 94, 46, 42, 86, 54, 16]])

In [79]:
r.size

16

In [80]:
b.size

9

In [81]:
np.max(r)

95

In [82]:
np.sum(r)

866

In [83]:
r.sum()

866

In [84]:
r.sum(1)

array([127, 276, 265, 198])

In [85]:
r.sum(0)

array([239, 211, 251, 165])

In [86]:
r.sum(axis=0)

array([239, 211, 251, 165])

In [87]:
r.sum(axis=1)

array([127, 276, 265, 198])

In [88]:
r.mean()

54.125

In [89]:
r.all()

True

In [90]:
b.all()

False

In [91]:
a.all()

True

In [92]:
x = np.random.randint(1,10,(3,3))

In [93]:
y = np.ones((1,3))

In [94]:
x

array([[4, 6, 2],
       [7, 5, 6],
       [7, 3, 5]])

In [95]:
y

array([[1., 1., 1.]])

In [96]:
#Broardcasting
x+y

array([[5., 7., 3.],
       [8., 6., 7.],
       [8., 4., 6.]])

In [97]:
y = [[1,2,3]]

In [98]:
y

[[1, 2, 3]]

In [99]:
x+y

array([[5, 8, 5],
       [8, 7, 9],
       [8, 5, 8]])